---
image: duneci/docker-builder

stages:
 - stage0
 - stage1
 - stage2
 - stage3
 - publish

pull base distributions:
 stage: stage0
 script:
 - docker pull debian:8
 - docker pull debian:stretch
 - docker pull ubuntu:16.04
 - docker pull ubuntu:16.10
 only:
 - master@ansgar/dune-docker

docker-builder:
 stage: stage1
 script:
 - ./bin/duneci-build-docker-image duneci/docker-builder docker-builder
 only:
 - master@ansgar/dune-docker

base:8:
 stage: stage1
 script:
 - ./bin/duneci-build-docker-image duneci/base:8 base-common base-8
 only:
 - master@ansgar/dune-docker

base:9:
 stage: stage1
 script:
 - ./bin/duneci-build-docker-image duneci/base:9 base-common base-9
 only:
 - master@ansgar/dune-docker

base:16.04:
 stage: stage1
 script:
 - ./bin/duneci-build-docker-image duneci/base:16.04 base-common base-16.04
 only:
 - master@ansgar/dune-docker

base:16.10:
 stage: stage1
 script:
 - ./bin/duneci-build-docker-image duneci/base:16.10 base-common base-16.10
 only:
 - master@ansgar/dune-docker

base:8-backports:
 stage: stage2
 script:
 - ./bin/duneci-build-docker-image duneci/base:8-backports base-8-backports
 only:
 - master@ansgar/dune-docker

dune:2.3:
 stage: stage2
 script:
 - ./bin/duneci-build-docker-image duneci/dune:2.3 dune-2.3
 only:
 - master@ansgar/dune-docker

dune:2.4:
 stage: stage2
 script:
 - ./bin/duneci-build-docker-image duneci/dune:2.4 dune-2.4
 only:
 - master@ansgar/dune-docker

dune:2.5:
 stage: stage2
 script:
 - ./bin/duneci-build-docker-image --no-cache duneci/dune:2.5 dune-2.5
 only:
 - master@ansgar/dune-docker

dune:git:
 stage: stage2
 script:
 - ./bin/duneci-build-docker-image --no-cache duneci/dune:git dune-git
 only:
 - master@ansgar/dune-docker

dune-fufem:2.4:
 stage: stage3
 script:
 - ./bin/duneci-build-docker-image duneci/dune-fufem dune-fufem
 only:
 - master@ansgar/dune-docker

dune-fufem:git:
 stage: stage3
 script:
 - ./bin/duneci-build-docker-image --no-cache duneci/dune-fufem-git dune-fufem-git
 only:
 - master@ansgar/dune-docker

publish:
 stage: publish
 script:
 - docker push duneci/base:8
 - docker push duneci/base:9
 - docker push duneci/base:16.04
 - docker push duneci/base:16.10
 - docker push duneci/base:8-backports
 - docker push duneci/dune:2.3
 - docker push duneci/dune:2.4
 - docker push duneci/dune:2.5
 - docker push duneci/dune:git
 - docker push duneci/dune-fufem:2.4
 - docker push duneci/dune-fufem:git
 only:
 - master@ansgar/dune-docker
