---

stages:
  - service
  - base
  - core
  - modules
  - finalize
  - rollback


# ---------------------------------------------------------------------
#
# common variables for the various stages
#
# ---------------------------------------------------------------------

.service-variables:
  variables: &service-variables
    DUNECI_DOCKER_CACHE_SERVICE: 1
    CORES: 1

.base-variables:
  variables: &base-variables
    IMAGE: $CI_REGISTRY_IMAGE/$DISTRO:$VERSION
    SOURCE_DIRS: base-common $DISTRO-$VERSION
    DUNECI_DOCKER_CACHE_BASE: 1
    CORES: 1

.core-variables:
  variables: &core-variables
    IMAGE: $CI_REGISTRY_IMAGE/dune:$VERSION
    SOURCE_DIRS: dune-$VERSION
    BUILD_ARGS: --parallel
    DUNECI_DOCKER_CACHE_CORE: 1
    CORES: 4

.module-variables:
  variables: &module-variables
    IMAGE: $CI_REGISTRY_IMAGE/dune-$MODULE:$VERSION
    SOURCE_DIRS: dune-$MODULE-$VERSION
    BUILD_ARGS: --parallel
    DUNECI_DOCKER_CACHE_MODULES: 1
    CORES: 4


# ---------------------------------------------------------------------
#
# Base template for all jobs that build a Docker image
#
# ---------------------------------------------------------------------


.base: &base
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin=true $CI_REGISTRY
  script:
    - echo "Building $IMAGE..."
    - ./bin/duneci-build-docker-image $BUILD_ARGS $IMAGE $SOURCE_DIRS
  artifacts:
    paths:
      - output/images/
    expire_in: 1d
  tags:
    - "services:dind"
    - "dind:cores:4"
  only:
    refs:
      - branches@docker/images


# ---------------------------------------------------------------------
#
# image templates for the various stages
#
# ---------------------------------------------------------------------


.service-image: &service-image
  <<: *base
  stage: service

.base-image: &base-image
  <<: *base
  stage: base

.core-image: &core-image
  <<: *base
  stage: core

.module-image: &module-image
  <<: *base
  stage: modules


# ---------------------------------------------------------------------
#
# service images
#
# ---------------------------------------------------------------------


docker:
  <<: *service-image
  variables:
    <<: *service-variables
    IMAGE: $CI_REGISTRY_IMAGE/service/docker:latest
    SOURCE_DIRS: docker


# ---------------------------------------------------------------------
#
# base images
#
# ---------------------------------------------------------------------


debian:9:
  <<: *base-image
  variables:
    <<: *base-variables
    DISTRO: debian
    VERSION: 9

debian:10:
  <<: *base-image
  variables:
    <<: *base-variables
    DISTRO: debian
    VERSION: 10

ubuntu:16.04:
  <<: *base-image
  variables:
    <<: *base-variables
    DISTRO: ubuntu
    VERSION: "16.04"

ubuntu:18.04:
  <<: *base-image
  variables:
    <<: *base-variables
    DISTRO: ubuntu
    VERSION: "18.04"


# ---------------------------------------------------------------------
#
# core images
#
# ---------------------------------------------------------------------


dune:git:
  <<: *core-image
  variables:
    <<: *core-variables
    VERSION: "git"

dune:2.4:
  <<: *core-image
  variables:
    <<: *core-variables
    VERSION: "2.4"

dune:2.5:
  <<: *core-image
  variables:
    <<: *core-variables
    VERSION: "2.5"

dune:2.6:
  <<: *core-image
  variables:
    <<: *core-variables
    VERSION: "2.6"


# ---------------------------------------------------------------------
#
# module images
#
# ---------------------------------------------------------------------


dune-fufem:2.4:
  <<: *module-image
  variables:
    <<: *module-variables
    MODULE: fufem
    VERSION: "2.4"

dune-fufem:git:
  <<: *module-image
  variables:
    <<: *module-variables
    MODULE: fufem
    VERSION: "git"

dune-pdelab-deps:2.6:
  <<: *module-image
  variables:
    <<: *module-variables
    MODULE: pdelab-deps
    VERSION: "2.6"

dune-pdelab-deps:git:
  <<: *module-image
  variables:
    <<: *module-variables
    MODULE: pdelab-deps
    VERSION: "git"


# ---------------------------------------------------------------------
#
# deploy / cleanup
#
# ---------------------------------------------------------------------


cleanup-temp-images:
  stage: finalize
  image: $CI_REGISTRY_IMAGE/service/docker:latest
  variables:
    CORES: 1
  script:
    - ./bin/duneci-process-images cleanup
  tags:
    - "site:hd"
    - "cores:1"
  only:
    refs:
      - branches@docker/images
  except:
    refs:
      - master@docker/images

deploy:
  environment:
    name: production
    url: https://gitlab.dune-project.org/docker/ci/container_registry
  stage: finalize
  image: $CI_REGISTRY_IMAGE/service/docker:latest
  variables:
    CORES: 1
  script:
    - ./bin/duneci-process-images deploy
  tags:
    - "site:hd"
    - "cores:1"
  only:
    refs:
      - master@docker/images

restore-images:
  stage: rollback
  when: on_failure
  image: $CI_REGISTRY_IMAGE/service/docker:latest
  variables:
    CORES: 1
  script:
    - ./bin/duneci-process-images rollback
  tags:
    - "site:hd"
    - "cores:1"
  only:
    refs:
      - branches@docker/images
