#! /bin/bash

set -e
set -u

if [[ -n "${DUNECI_OPTS:-}" ]]; then
  set -- --opts="${DUNECI_OPTS}" "${@}"
fi

DUNECONTROL=dunecontrol
if [[ -x bin/dunecontrol ]]; then
  DUNECONTROL=bin/dunecontrol
fi

set -x
${DUNECONTROL} --current "${@}" all
${DUNECONTROL} --current make build_tests
cd build-cmake
dune-ctest
